// Code generated by protoc-gen-go. DO NOT EDIT.
// source: voting/protobuf/voting/vote.proto

package voting

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Candidate Status represents status of a candidate
type CandidateStatus int32

const (
	CandidateStatus_QUALIFIED    CandidateStatus = 0
	CandidateStatus_DISQUALIFIED CandidateStatus = 1
)

var CandidateStatus_name = map[int32]string{
	0: "QUALIFIED",
	1: "DISQUALIFIED",
}

var CandidateStatus_value = map[string]int32{
	"QUALIFIED":    0,
	"DISQUALIFIED": 1,
}

func (x CandidateStatus) String() string {
	return proto.EnumName(CandidateStatus_name, int32(x))
}

func (CandidateStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c26e0abe7c32465, []int{0}
}

// Vote represents the settings of a vote
type Vote struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Candidates           []*Candidate `protobuf:"bytes,4,rep,name=candidates,proto3" json:"candidates,omitempty"`
	StartAt              int64        `protobuf:"varint,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                int64        `protobuf:"varint,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	UpdatedAt            int64        `protobuf:"varint,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            int64        `protobuf:"varint,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c26e0abe7c32465, []int{0}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vote) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vote) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Vote) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *Vote) GetStartAt() int64 {
	if m != nil {
		return m.StartAt
	}
	return 0
}

func (m *Vote) GetEndAt() int64 {
	if m != nil {
		return m.EndAt
	}
	return 0
}

func (m *Vote) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Vote) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// Candidate represents a candidate participated in a vote
type Candidate struct {
	Code                 string          `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status               CandidateStatus `protobuf:"varint,4,opt,name=status,proto3,enum=voting.CandidateStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c26e0abe7c32465, []int{1}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Candidate) GetStatus() CandidateStatus {
	if m != nil {
		return m.Status
	}
	return CandidateStatus_QUALIFIED
}

func init() {
	proto.RegisterEnum("voting.CandidateStatus", CandidateStatus_name, CandidateStatus_value)
	proto.RegisterType((*Vote)(nil), "voting.Vote")
	proto.RegisterType((*Candidate)(nil), "voting.Candidate")
}

func init() { proto.RegisterFile("voting/protobuf/voting/vote.proto", fileDescriptor_8c26e0abe7c32465) }

var fileDescriptor_8c26e0abe7c32465 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4e, 0xab, 0x40,
	0x14, 0x86, 0xef, 0x14, 0xca, 0x95, 0x53, 0xa5, 0x75, 0x12, 0x23, 0x2e, 0x4c, 0xb0, 0x2b, 0xe2,
	0x02, 0x22, 0x3e, 0x01, 0xb1, 0x9a, 0x90, 0xb8, 0x91, 0x46, 0xb7, 0x66, 0xca, 0x8c, 0x66, 0x16,
	0xce, 0x10, 0x38, 0xf4, 0x11, 0x7c, 0x5d, 0x5f, 0xc1, 0x70, 0xa0, 0xda, 0xe8, 0xce, 0xdd, 0x39,
	0xdf, 0xf7, 0x4f, 0x66, 0xfe, 0x0c, 0x5c, 0x6c, 0x2d, 0x6a, 0xf3, 0x9a, 0xd6, 0x8d, 0x45, 0xbb,
	0xe9, 0x5e, 0xd2, 0x71, 0xdf, 0x5a, 0x54, 0x09, 0x41, 0xee, 0x0d, 0x68, 0xf9, 0xc1, 0xc0, 0x7d,
	0xb2, 0xa8, 0x78, 0x00, 0x13, 0x2d, 0x43, 0x16, 0xb1, 0xd8, 0x2f, 0x27, 0x5a, 0x72, 0x0e, 0xae,
	0x11, 0x6f, 0x2a, 0x9c, 0x10, 0xa1, 0x99, 0x47, 0x30, 0x93, 0xaa, 0xad, 0x1a, 0x5d, 0xa3, 0xb6,
	0x26, 0x74, 0x48, 0xed, 0x23, 0x7e, 0x05, 0x50, 0x09, 0x23, 0xb5, 0x14, 0xa8, 0xda, 0xd0, 0x8d,
	0x9c, 0x78, 0x96, 0x1d, 0x27, 0xc3, 0x5d, 0xc9, 0xcd, 0xce, 0x94, 0x7b, 0x21, 0x7e, 0x06, 0x07,
	0x2d, 0x8a, 0x06, 0x9f, 0x05, 0x86, 0xd3, 0x88, 0xc5, 0x4e, 0xf9, 0x9f, 0xf6, 0x1c, 0xf9, 0x09,
	0x78, 0xca, 0xc8, 0x5e, 0x78, 0x24, 0xa6, 0xca, 0xc8, 0x1c, 0xf9, 0x39, 0x40, 0x57, 0xf7, 0x87,
	0x49, 0x05, 0xa4, 0xfc, 0x91, 0x0c, 0xba, 0x6a, 0xd4, 0x4e, 0xcf, 0x07, 0x3d, 0x92, 0x1c, 0x97,
	0xef, 0x0c, 0xfc, 0xaf, 0x97, 0xf4, 0x35, 0x2b, 0x2b, 0xd5, 0x58, 0x9c, 0xe6, 0x3f, 0x56, 0x4f,
	0xc1, 0x6b, 0x51, 0x60, 0xd7, 0xd7, 0x66, 0x71, 0x90, 0x9d, 0xfe, 0xaa, 0xbd, 0x26, 0x5d, 0x8e,
	0xb1, 0xcb, 0x0c, 0xe6, 0x3f, 0x14, 0x3f, 0x02, 0xff, 0xe1, 0x31, 0xbf, 0x2f, 0xee, 0x8a, 0xdb,
	0xd5, 0xe2, 0x1f, 0x5f, 0xc0, 0xe1, 0xaa, 0x58, 0x7f, 0x13, 0xb6, 0xf1, 0xe8, 0xf7, 0xae, 0x3f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x33, 0xbd, 0x75, 0xe2, 0x01, 0x00, 0x00,
}
